export const levels: LevelConfig[] = [
    [
        { row: 0, col: 3, sound: 1 },
        { row: 1, col: 3, sound: 2 },
        { row: 2, col: 3, sound: 3 },
        { row: 1, col: 3, sound: 4 },
        { row: 0, col: 3, sound: 5 },
        { row: 1, col: 3, sound: 6 },
        { row: 2, col: 3, sound: 7 },
        { row: 1, col: 3, sound: 8 },
    ],
    [
        { row: 0, col: 3, sound: 1 },
        { row: 1, col: 3, sound: 1 },
        { row: 2, col: 3, sound: 1 },
        { row: 2, col: 3, sound: 1 },
    ],
    [
        { row: 0, col: 0, sound: 1 },
        { row: 0, col: 3, sound: 1 },
        { row: 1, col: 3, sound: 2 },
        { row: 2, col: 3, sound: 3 },
        { row: 1, col: 3, sound: 4 },
        { row: 1, col: 0, sound: 5 },
        { row: 0, col: 3, sound: 5 },
        { row: 1, col: 3, sound: 6 },
        { row: 2, col: 3, sound: 7 },
        { row: 1, col: 3, sound: 8 },
        { row: 2, col: 0, sound: 9 },
        { row: 0, col: 3, sound: 9 },
        { row: 1, col: 3, sound: 10 },
        { row: 2, col: 3, sound: 11 },
        { row: 1, col: 3, sound: 12 },
        { row: 2, col: 1, sound: 13 },
        { row: 0, col: 3, sound: 13 },
        { row: 1, col: 3, sound: 14 },
    ],
];
