/* eslint-disable @typescript-eslint/naming-convention */

export const sounds = {
    '1': '1',
    '10': '10',
    '11': '11',
    '12': '12',
    '2': '2',
    '3': '3',
    '4': '4',
    '5': '5',
    '6': '6',
    '7': '7',
    '8': '8',
    '9': '9',
    PadModel07: 'PadModel07',
    PadModel08: 'PadModel08',
    PadModel10: 'PadModel10',
    PadModel11: 'PadModel11',
    PadModel14: 'PadModel14',
    PadModel15: 'PadModel15',
    PadModel18: 'PadModel18',
    chime: 'chime',
    iceCreamAArp01: 'ice_cream_a_arp_01',
    iceCreamABell01: 'ice_cream_a_bell_01',
    iceCreamABell02: 'ice_cream_a_bell_02',
    iceCreamAChords01: 'ice_cream_a_chords_01',
    iceCreamAChords02: 'ice_cream_a_chords_02',
    iceCreamAChords03: 'ice_cream_a_chords_03',
    iceCreamAChords04: 'ice_cream_a_chords_04',
    iceCreamAHat01: 'ice_cream_a_hat_01',
    iceCreamAKick01: 'ice_cream_a_kick_01',
    iceCreamASnare01: 'ice_cream_a_snare_01',
    iceCreamAVocals01: 'ice_cream_a_vocals_01',
    iceCreamAVocals02: 'ice_cream_a_vocals_02',
    theme: 'theme',
};
